Use EShop

--This is a comment

--Get all Products
Select * from Product

--Get all products that has categoryId = 12
Select * from Product
Where CategoryId = 12

--Get total cost of products listed with categoryId = 12
Select Sum(Cost) from Product
Where CategoryId = 12

--Get product name, cost from product table
Select Name, Cost from Product

--Save above as view
Create VIEW vw_Product AS
(Select Name, Cost from Product)

--See the view
Select * from vw_Product

--Get all products that starts with "B"
Select * from Product
Where Name Like 'L%'

--Get all the products that have the seconld character as "e"
Select * from Product
Where Name Like '_e%'

--Get all products whose cost is not equal to 1100
Select * from Product
Where Cost <> 1100

--'^%s$' => This word starts (^) with any character and contains 's' at the end ($)
--Strats with anything , has J in a word and ends with a
Select * from Product
Where Name like '%j%a'

--Select all products with names AS "Lehanga", 'skirt'
Select * from Product
Where Name = 'Lehanga'OR Name = 'Jumka'

--Better technique 
Select * from Product
Where Name in ('Lehanga','Jumka')

--Get all products having a  category id matching in productcategory table
Select * from Product
Where CategoryId IN (Select  Id from ProductCategory)

--Get Customer NNmae and Order Id for all Customers
--Customer table has customer name
--Order Id is in Orders table
Select [Name], [OrderId] from Customer, Orders
Where Customer.id = Orders.CustomerId

--Get total revenue generated by Anna'
--Customer Nmae from Customer table
---Total cost from product
--Orders table contains Customer purchases

Select SUM(Cost)
From Orders, Customer, Product
Where Orders.CustomerId = Customer.Id
And Orders.ProductId = ProductId
And Customer.Name = 'Anna'

